export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const NAVBAR_TOGGLE = "NAVBAR_TOGGLE";
export const NAVBAR_OPEN = "NAVBAR_OPEN";
export const NAVBAR_CLOSE = "NAVBAR_CLOSE";

export const LOGIN_TOGGLE = "LOGIN_TOGGLE";
export const LOGIN_OPEN = "LOGIN_OPEN";
export const LOGIN_CLOSE = "LOGIN_CLOSE";

export const REGISTER_TOGGLE = "REGISTER_TOGGLE";
export const REGISTER_OPEN = "REGISTER_OPEN";
export const REGISTER_CLOSE = "REGISTER_CLOSE";

export const PROFILEIMAGE_TOGGLE = "PROFILEIMAGE_TOGGLE";
export const PROFILEIMAGE_OPEN = "PROFILEIMAGE_OPEN";
export const PROFILEIMAGE_CLOSE = "PROFILEIMAGE_CLOSE";

export const GROUPCHATCREATOR_TOGGLE = "GROUPCHATCREATOR_TOGGLE";
export const GROUPCHATCREATOR_OPEN = "GROUPCHATCREATOR_OPEN";
export const GROUPCHATCREATOR_CLOSE = "GROUPCHATCREATOR_CLOSE";

export const ROOMISACTIVE = "ROOMISACTIVE";
export const ROOMISINACTIVE = "ROOMISINACTIVE";
export const ROOM_TOGGLE = "ROOM_TOGGLE";

export const SHOULD_LAUNCH_MODAL = "SHOULD_LAUNCH_MODAL";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_CHATS = "GET_ALL_CHATS";
export const SET_ACTIVE_CHAT = "SET_ACTIVE_CHAT";
export const SET_INITIAL_LIST = "SET_INITIAL_LIST";
export const CLEAR_LIST = "CLEAR_LIST";
export const RESET_LENGTH = "RESET_LENGTH";
export const HANDLE_LOAD = "HANDLE_LOAD";
export const LOAD_MORE = "LOAD_MORE";
