export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const NAVBAR_TOGGLE = "NAVBAR_TOGGLE";
export const NAVBAR_OPEN = "NAVBAR_OPEN";
export const NAVBAR_CLOSE = "NAVBAR_CLOSE";

export const LOGIN_TOGGLE = "LOGIN_TOGGLE";
export const LOGIN_OPEN = "LOGIN_OPEN";
export const LOGIN_CLOSE = "LOGIN_CLOSE";

export const REGISTER_TOGGLE = "REGISTER_TOGGLE";
export const REGISTER_OPEN = "REGISTER_OPEN";
export const REGISTER_CLOSE = "REGISTER_CLOSE";
